// Edit this file to update the Experience timeline page.
// Tags: 'venture' | 'ai' | 'product' | 'community' | 'early'
// Year values drive grouping — entries with the same year are grouped together.

export const timelineEntries = [
  {
    id: 1,
    year: 'Now',
    tags: ['venture'],
    title: 'Operating Partner, Velocity Catalyst Fund',
    date: '2025 – Present',
    body: 'Pre-seed VC firm backing Chicago-rooted founders. Working across capital formation, LP relations, and fund operations — serving as a hands-on strategic resource to portfolio founders across go-to-market, finance, and early company-building decisions.',
    learned: 'Operator by nature. Investor by conviction.',
  },
  {
    id: 2,
    year: 'Now',
    tags: ['venture', 'ai'],
    title: 'Director, Venture Studio & Faculty — Equitech Futures',
    date: 'March 2023 – Present',
    body: 'Managing and deploying capital across a portfolio of 8 AI ventures. Co-leading fundraising for a $2M annual operating budget — secured $289K in philanthropic funding in 2025. Launched the Kevin Xu Innovation Challenge with the Rhodes Trust, evaluating 50+ applications and allocating $40K in grants.',
    learned: 'How to build a venture portfolio from scratch and make milestone-based funding decisions with rigor and care.',
  },
  {
    id: 3,
    year: 'Now',
    tags: ['ai', 'product'],
    title: 'Principal Consultant, AI & Social Impact — Kinning Consulting',
    date: 'March 2023 – Present',
    body: 'Built an app for Belong Center that launched at SXSW with 300 users. Built investment workflow tools for Josephine Collective (50% time savings). Building custom AI agents for a pre-seed VC. Designed an AI executive training program for a global hedge fund.',
    learned: 'How to build AI tools that actually get used — not just demoed.',
  },
  {
    id: 4,
    year: '2023',
    tags: ['venture', 'community'],
    title: 'Spoke at Oxford — Tech and Society Forum',
    date: '2023',
    body: 'Panelist at Oxford University\'s Tech and Society Forum discussing how strategic investments can ignite innovation and drive meaningful progress while delivering both financial returns and positive societal impact.',
    learned: 'How to hold a room with a point of view, not just a résumé.',
  },
  {
    id: 5,
    year: '2023',
    tags: ['community', 'product'],
    title: 'Designed & Scaled Multi-Country Programs',
    date: '2023',
    body: 'Launched the Africa Data Challenge (20 water utilities, multiple governments) and the Innovation Institute (30+ builders from 15 countries). Programs spanning continents, making real infrastructure decisions.',
    learned: 'How to design programs that work across cultures, time zones, and political contexts.',
  },
  {
    id: 6,
    year: '2021',
    tags: ['product', 'venture'],
    title: 'Product Manager & Venture Accelerator Lead — Moon Creative Lab',
    date: 'July 2021 – Jan 2024',
    body: 'Product lead and ecosystem development strategist for an early-stage corporate venture incubator (Palo Alto/Tokyo). Led a startup in Manila building an on-demand childcare marketplace through end-to-end pre-seed venture design. Built the first company-wide training curriculum for entrepreneurs-in-residence.',
    learned: 'How to lead multidisciplinary teams across the US, Japan, and Southeast Asia — and that cross-cultural product work requires humility before strategy.',
  },
  {
    id: 7,
    year: '2021',
    tags: ['early'],
    title: 'Graduated Booth — MBA in Behavioral Science, Entrepreneurship & Strategy',
    date: '2021',
    body: 'Chicago Booth, University of Chicago. Tried to co-found my first startup simultaneously. Learned that momentum is everything and that business school is what you make of it.',
    learned: 'How to time manage to the extreme — and that an MBA isn\'t just for investment bankers.',
  },
  {
    id: 8,
    year: '2020',
    tags: ['ai', 'product'],
    title: 'Research Assistant & PM — Center for Applied AI, UChicago',
    date: 'Nov 2019 – June 2021',
    body: 'Researcher and project manager for computational medicine legal infrastructure, a COVID-19 public policy tool, and AI applications for human capital assessment. Built a coalition of researchers, lawyers, and data governance professionals across the country.',
    learned: 'How to move incredibly quickly and translate academic research into things people actually use.',
  },
  {
    id: 9,
    year: '2019',
    tags: ['community'],
    title: 'Associate Director, Alumni Career Programs — University of Chicago',
    date: 'Oct 2016 – July 2021',
    body: 'Engagement strategy and career team manager for 180K UChicago alumni worldwide. Managed global programming for 10K+ alumni annually. Coordinated alumni affinity groups to strengthen leadership giving by 62% and created an inaugural scholarship fund for public-interest law students.',
    learned: 'How to build communities that sustain themselves — and that volunteers are the most powerful force in any organization.',
  },
  {
    id: 10,
    year: '2018',
    tags: ['early'],
    title: 'Pivoted from theatre directing to the corporate world',
    date: '2018',
    body: 'A stint in mortgage banking, then University Development. Not the obvious next step from directing plays — but the translation turned out to be the whole point.',
    learned: 'How to navigate the corporate world and translate experiences across domains that don\'t obviously connect.',
  },
  {
    id: 11,
    year: '2013',
    tags: ['early', 'community'],
    title: 'Founded a theatre company. Graduated. Moved to Chicago.',
    date: '2013–2016',
    body: 'Founded a theatre company focused on creating opportunities for directors to practice their craft. Graduated undergrad at Ball State (BS, Theatre Directing). Moved to Chicago. Worked service jobs to support unpaid theatre work.',
    learned: 'How to build something with friends, find a unique need, differentiate yourself — and how to hustle.',
  },
  {
    id: 12,
    year: 'The Beginning',
    tags: ['early'],
    title: 'Founded my own country in the backyard',
    date: 'Childhood',
    body: 'Complete with its own currency and local dress. This is not a metaphor.',
    learned: 'How to have a very big vision and start one step at a time.',
  },
  {
    id: 13,
    year: 'The Beginning',
    tags: ['early'],
    title: 'Born a first-born Capricorn',
    date: 'The start',
    body: 'Learned immediately how to be a leader and not apologize for being ambitious. Some things are just in the bones.',
    learned: 'How to be a leader and not apologize for being ambitious.',
  },
  {
    id: 14,
    year: 'The Beginning',
    tags: ['early'],
    title: 'Wanted to be a pioneer. In a covered wagon. Making medicine from plants.',
    date: 'Childhood',
    body: 'Spent a lot of time in the woods. Read a lot of books. Worked every day after school at the local gastropub. Built an identity as an explorer before knowing what that meant professionally.',
    learned: 'How to be at home in the woods and identify as an explorer.',
  },
]
